-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 17:51:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `paymybuddy`;

CREATE SCHEMA IF NOT EXISTS `paymybuddy` DEFAULT CHARACTER SET utf8 ;
USE `paymybuddy` ;

-- -----------------------------------------------------
-- Table `paymybuddy`.`app_role`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `paymybuddy`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)
  );

-- -----------------------------------------------------
-- Table `paymybuddy`.`app_user`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `paymybuddy`.`app_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `balance` DECIMAL(10,2) UNSIGNED NOT NULL,
  `active_email` VARCHAR(100) GENERATED ALWAYS AS (CASE WHEN deleted_at IS NULL THEN email ELSE NULL END) STORED,
  `role` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_role` 
  FOREIGN KEY (`role`)
  REFERENCES `paymybuddy`.`role` (`id`),
  UNIQUE INDEX `active_email_UNIQUE` (`active_email` ASC));

-- -----------------------------------------------------
-- Table `paymybuddy`.`transfer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`transfer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sender` INT UNSIGNED NOT NULL,
  `receiver` INT UNSIGNED NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(10,2) UNSIGNED NOT NULL,
  `fees` DECIMAL(10,3) UNSIGNED NOT NULL DEFAULT 0.005,
  `total_amount` DECIMAL(10,2) GENERATED ALWAYS AS (ROUND(amount * (1+fees), 2)) STORED,
  `date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transfer_sender_idx` (`sender` ASC),
  INDEX `fk_transfer_receiver_idx` (`receiver` ASC),
  INDEX `total_amount_idx` (`total_amount` ASC),
  CONSTRAINT `fk_transfer_sender`
    FOREIGN KEY (`sender`)
    REFERENCES `paymybuddy`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transfer_receiver`
    FOREIGN KEY (`receiver`)
    REFERENCES `paymybuddy`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `paymybuddy`.`user_beneficiary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paymybuddy`.`user_beneficiary` (
  `user_id` INT UNSIGNED NOT NULL,
  `beneficiary_id` INT UNSIGNED NOT NULL,
  INDEX `fk_userbeneficiary_user_id_idx` (`user_id` ASC),
  INDEX `fk_userbeneficiary_beneficiary_id_idx` (`beneficiary_id` ASC),
  PRIMARY KEY (`user_id`, `beneficiary_id`),
  CONSTRAINT `fk_userbeneficiary_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `paymybuddy`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_userbeneficiary_beneficiary_id`
    FOREIGN KEY (`beneficiary_id`)
    REFERENCES `paymybuddy`.`app_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `paymybuddy`.`role`
-- -----------------------------------------------------
INSERT INTO `role` (id, name) 
VALUES (1, 'ROLE_USER'), (2, 'ROLE_ADMIN');


-- -----------------------------------------------------
-- Data for table `paymybuddy`.`app_user`
-- -----------------------------------------------------
INSERT INTO `paymybuddy`.`app_user` (`username`, `email`, `deleted_at`, `password`, `balance`, `role`) 
SELECT * FROM (SELECT 'Georgia', 'georgia@email.com', NULL, '$2a$10$Lc2JhT8glUB8.hfGoRYGVuuDnL7RM8XXSLAQTYlmv5hlNkkE14BQu', 100.00, 1) AS tmp
WHERE NOT EXISTS(
	SELECT 1 FROM `paymybuddy`.`app_user` WHERE active_email = 'georgia@email.com'
	)
LIMIT 1;

INSERT INTO `paymybuddy`.`app_user` (`username`, `email`, `deleted_at`, `password`, `balance`, `role`) 
SELECT * FROM (SELECT 'Tanka', 'tanka@email.com', NULL, '$2a$10$tOwIV5x8bXF/Xh5tkHkKmO153X8bSGkibFU21KK6oshF1R9mVS6KO', 100.00, 1) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`app_user` WHERE active_email = 'tanka@email.com'
)
LIMIT 1;

INSERT INTO `paymybuddy`.`app_user` (`username`, `email`, `deleted_at`, `password`, `balance`, `role`)
SELECT * FROM (SELECT 'Bagheera', 'bagheera@email.com', NULL, '$2a$10$1CLQi6XqmrfmafzzfeO/jOhGfnY6F4vIk5lbyQh7aSKN7VS.0mIdi', 100.00, 1) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`app_user` WHERE active_email = 'bagheera@email.com'
)
LIMIT 1;

INSERT INTO `paymybuddy`.`app_user` (`username`, `email`, `deleted_at`, `password`, `balance`, `role`)
SELECT * FROM (SELECT 'Mania', 'mania@email.com', NULL, '$2a$10$OrZrQGi2o7nb1eRzZfgWFOdm9LksYYirAfjb3Agdf9if30eNWhEom', 100.00, 1) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`app_user` WHERE active_email = 'mania@email.com'
)
LIMIT 1;

INSERT INTO `paymybuddy`.`app_user` (`username`, `email`, `deleted_at`, `password`, `balance`, `role`)
SELECT * FROM (SELECT 'Jeena', 'jeena@email.com', NULL, '$2a$10$E3MsEXGQJfKhtRwBWCQjoeOHrGXH2AqN15RhOjQu1GirCdMcNRrTG', 100.00, 1) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`app_user` WHERE active_email = 'jeena@email.com'
)
LIMIT 1;

-- -----------------------------------------------------
-- Data for table `paymybuddy`.`user_beneficiary`
-- -----------------------------------------------------
INSERT INTO `paymybuddy`.`user_beneficiary` (`user_id`, `beneficiary_id`)
SELECT * FROM (SELECT 1, 2) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`user_beneficiary` WHERE user_id = 1 AND beneficiary_id = 2
)
LIMIT 1;

INSERT INTO `paymybuddy`.`user_beneficiary` (`user_id`, `beneficiary_id`)
SELECT * FROM (SELECT 1, 3) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`user_beneficiary` WHERE user_id = 1 AND beneficiary_id = 3
)
LIMIT 1;

INSERT INTO `paymybuddy`.`user_beneficiary` (`user_id`, `beneficiary_id`)
SELECT * FROM (SELECT 3, 4) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`user_beneficiary` WHERE user_id = 3 AND beneficiary_id = 4
)
LIMIT 1;
-- -----------------------------------------------------
-- Update table `paymybuddy`.`transfer`
-- -----------------------------------------------------

START TRANSACTION;
USE `paymybuddy`;

INSERT INTO `paymybuddy`.`transfer` (`sender`, `receiver`, `description`, `amount`, `date`) 
SELECT * FROM (SELECT 1, 2, 'entrée parc aquatique', 18, NOW()) AS tmp
WHERE NOT EXISTS (
	SELECT 1 FROM `paymybuddy`.`transfer`
	WHERE sender = 1
	  AND receiver = 2
	  AND description = 'entrée parc aquatique'
	  AND amount = 18
	  AND DATE(date) = CURDATE()
)
LIMIT 1;

-- -----------------------------------------------------
-- Update app_user (sender) balance after transfer
-- -----------------------------------------------------
UPDATE `paymybuddy`.`app_user` u
SET u.balance = u.balance - 18 * (1 + 0.005)
WHERE u.id = 1;

-- -----------------------------------------------------
-- Update app_user (beneficier) balance after transfer
-- -----------------------------------------------------
UPDATE `paymybuddy`.`app_user` u
SET u.balance = u.balance + 18
WHERE u.id = 2;

COMMIT;